# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='design',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='usability',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
